sonar.projectKey=alumni_portal_project
sonar.projectName=Alumni Portal
sonar.projectVersion=1.0

# YOUR COLLEGE SONARQUBE CREDENTIALS
sonar.host.url=http://sonarqube.imcc.com/
sonar.login=student
sonar.password=Imccstudent@2025

sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/venv/**, **/migrations/**, **/static/**, **/media/**, manage.py, coverage.xml
sonar.python.version=3.11