sonar.projectKey=alumni_portal_project
sonar.projectName=Alumni Portal
sonar.projectVersion=1.0

# Path to source directories
sonar.sources=.
sonar.sourceEncoding=UTF-8

# Exclude files from scan
sonar.exclusions=**/venv/**, **/migrations/**, **/static/**, **/media/**, manage.py

# Python version
sonar.python.version=3.11