apiVersion: apps/v1
kind: Deployment
metadata:
  name: alumni-portal
  labels:
    app: alumni-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alumni-portal
  template:
    metadata:
      labels:
        app: alumni-portal
    spec:
      containers:
      - name: alumni-portal
        image: 127.0.0.1:30085/2401192-project/alumni-portal:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        # Secure settings for production
        - name: DJANGO_SECRET_KEY
          value: "django-insecure-prod-key-change-this"
        - name: DEBUG
          value: "False"
---
apiVersion: v1
kind: Service
metadata:
  name: alumni-service
spec:
  type: NodePort
  selector:
    app: alumni-portal
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alumni-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: 2401192.imcc.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: alumni-service
            port:
              number: 8000
      