apiVersion: apps/v1
kind: Deployment
metadata:
  name: alumni-portal
  labels:
    app: alumni-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alumni-portal
  template:
    metadata:
      labels:
        app: alumni-portal
    spec:
      containers:
      - name: alumni-portal
        # Points to the image we just pushed to Nexus
        image: nexus.imcc.com/2401192/alumni-portal:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        # Secure settings for production
        - name: DJANGO_SECRET_KEY
          value: "django-insecure-prod-key-change-this"
        - name: DEBUG
          value: "False"
---
apiVersion: v1
kind: Service
metadata:
  name: alumni-service
spec:
  type: NodePort # Exposes it outside the cluster
  selector:
    app: alumni-portal
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      