# Generated by Django 5.2.8 on 2025-11-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='enrollment_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
